#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
df = pd.read_csv(r"C:\Users\pgoku\Downloads\Dataset .csv")
print(df.head())


# In[2]:


rows, cols = df.shape
print(f'The dataset contains {rows} rows and {cols} columns.')


# In[3]:


missing_values = df.isnull().sum()
print(missing_values)
df = df.dropna() 


# In[4]:


print(df.dtypes)


# In[6]:


import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Aggregate rating'], kde=True)
plt.title('Distribution of Aggregate Rating')
plt.xlabel('Aggregate Rating')
plt.ylabel('Frequency')
plt.show()

class_counts = df['Aggregate rating'].value_counts()
print(class_counts)


# In[ ]:




